import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/app/components/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import { Header } from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header />

        {children}

        <Footer
          iconsSize={35}
          links={{
            instagram: "https://google.com",
            facebook: "https://google.com",
            linkedIn: "https://google.com",
          }}
          email={"sla@gmail.com"}
          image={{
            path: "/img/logo.png",
            alt: "Isso eh a logo foda no footer",
            size: 200,
          }}
        />
      </body>
    </html>
  );
}
